name: CI

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  checks: write

jobs:
  common-build:
    uses: GateNLP/gate-top/.github/workflows/standard-module.yml@master
    secrets: inherit
